"""
MediMind – FastAPI Backend
---------------------------
Main entry point for the MediMind API server.

Endpoints:
  GET  /health   → Health check (used by Render to verify the server is running)
  POST /analyze  → Accept symptoms, call Groq, return educational guidance

Run locally:
  uvicorn main:app --reload --port 8000

API docs (auto-generated by FastAPI):
  http://localhost:8000/docs
"""

from datetime import datetime, timezone

from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse

from config import settings
from models.schemas import (
    AnalyzeRequest,
    AnalyzeResponse,
    ErrorResponse,
    GuidanceContent,
)
from services.groq_service import generate_health_guidance
from services.prompt_builder import check_emergency_keywords


# ===== CREATE FASTAPI APP =====
app = FastAPI(
    title="MediMind API",
    description=(
        "Backend API for MediMind – AI Healthcare Assistant. "
        "Provides educational health guidance using Groq LLM. "
        "NOT a medical diagnosis tool."
    ),
    version="1.0.0",
)


# ===== CORS MIDDLEWARE =====
# Allows the frontend (on a different URL/port) to call this API.
# Without CORS, browsers block cross-origin requests for security.

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.ALLOWED_ORIGINS,  # Frontend URLs from .env
    allow_credentials=True,
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


# ===== ERROR HANDLERS =====
# Return consistent JSON error format that the frontend expects.

@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    """Converts HTTPException into our standard { success, error, code } format."""
    detail = exc.detail
    if isinstance(detail, dict):
        return JSONResponse(status_code=exc.status_code, content=detail)
    return JSONResponse(
        status_code=exc.status_code,
        content={"success": False, "error": str(detail), "code": "HTTP_ERROR"},
    )


@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    """Handles invalid request data (e.g. missing symptoms field)."""
    return JSONResponse(
        status_code=400,
        content={
            "success": False,
            "error": "Invalid request. Please check your symptom input.",
            "code": "VALIDATION_ERROR",
        },
    )


# ===== ROUTES =====

@app.get("/health")
def health_check():
    """
    Simple health check endpoint.
    Render uses this to confirm the server is alive.
    """
    return {
        "status": "healthy",
        "service": "MediMind API",
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


@app.post(
    "/analyze",
    response_model=AnalyzeResponse,
    responses={
        400: {"model": ErrorResponse},
        500: {"model": ErrorResponse},
    },
)
def analyze_symptoms(request: AnalyzeRequest):
    """
    Main endpoint: receives symptoms and returns AI-generated educational guidance.

    Flow:
      1. Validate input (handled automatically by Pydantic)
      2. Check for emergency keywords
      3. Call Groq API via groq_service
      4. Return structured JSON response to the frontend
    """

    # Extra validation: symptoms must not be empty after trimming
    if not request.symptoms.strip():
        raise HTTPException(
            status_code=400,
            detail={"success": False, "error": "Symptoms cannot be empty.", "code": "VALIDATION_ERROR"},
        )

    # Check if symptoms mention emergency-related keywords
    emergency_detected = check_emergency_keywords(request.symptoms)

    try:
        # Call Groq and get structured guidance
        guidance: GuidanceContent = generate_health_guidance(request)

    except ValueError as exc:
        # Configuration error (missing API key) or bad LLM response
        raise HTTPException(
            status_code=500,
            detail={"success": False, "error": str(exc), "code": "CONFIG_ERROR"},
        ) from exc

    except Exception as exc:
        print("\n========== ACTUAL GROQ ERROR ==========")
        import traceback
        traceback.print_exc()
        raise

    # Build and return the success response
    return AnalyzeResponse(
        success=True,
        guidance=guidance,
        disclaimer=settings.MEDICAL_DISCLAIMER,
        emergency_detected=emergency_detected,
        timestamp=datetime.now(timezone.utc).isoformat(),
    )


# ===== RUN DIRECTLY (optional) =====
# Allows: python main.py
if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
